import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextUIProviders, ReduxProvider } from "./providers";
import SideNav from "@/components/SideNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen flex`}>
        <ReduxProvider>
          <NextUIProviders>
            <main className="flex justify-between h-full w-full">
              <SideNav />
              {children}
            </main>
          </NextUIProviders>
        </ReduxProvider>
      </body>
    </html>
  );
}
